apiVersion: batch/v1
kind: CronJob
metadata:
  name: esc-trigger
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: triger
              image: esc-cron-app:latest
              imagePullPolicy: Never
              env:
                - name: REDIS_ADDR
                  value: "redis:6379"
                - name: REDIS_PWD
                  valueFrom:
                    secretKeyRef:
                      name: redis-password
                      key: redis-password
                - name: TARGET_HOST
                  value: "esc-target"
          restartPolicy: OnFailure
